--- #YAML:1.0
name:               CPAN-Test-Dummy-Perl5-NoBugTracker
version:            1.00
abstract:           CPAN Test Dummy that explicitly says there is no bug tracker
author:
    - Adam Kennedy <adamk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.004
resources:
    bugtracker:  
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
